POST http://localhost:5000/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic YW5ndWxhcjpAbmd1bEByMA==

client=angular&username=otanieljose30@gmail.com&password=octaniel&grant_type=password

> {% client.global.set("access_token", response.body.access_token); %}